artifacts:
  stackoverflow-dataset:
    path: data/data.xml
    type: dataset
    desc: Initial XML StackOverflow dataset (raw data)
  text-classification:
    path: model.pkl
    desc: Detect whether the given stackoverflow question should have R language tag
    type: model
    labels:
    - nlp
    - classification
    - stackoverflow
stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
  train:
    cmd: python src/train.py data/titanic/output train.pkl
    deps:
    - src/train.py
    outs:
    - data/titanic/output/train.pkl
# TODO: add evaluate script
# TODO: add metrics
# TODO: add plots
